CREATE TABLE `financial_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealId` varchar(50) NOT NULL,
	`estadoProyecto` varchar(100),
	`projectName` varchar(500),
	`clientName` varchar(255),
	`pm` varchar(255),
	`valorVentaUF` decimal(14,4),
	`presupuestoUF` decimal(14,4),
	`utilizadoUF` decimal(14,4),
	`utilizadoUFPorc` decimal(14,10),
	`presupuestoHH` decimal(14,4),
	`capacityHH` decimal(14,4),
	`hhPorcUtilizado` decimal(14,10),
	`margenBrutoNotaVentaUF` decimal(14,4),
	`porcentajeAvanceProyecto` decimal(14,10),
	`costoProyectadoUF` decimal(14,4),
	`margenProyectadoUF` decimal(14,4),
	`margenProyectadoPorc` decimal(14,10),
	`margenTargetPorc` decimal(14,10),
	`capacityU` decimal(14,4),
	`planificadoUF` decimal(14,4),
	`proyectadoUF` decimal(14,4),
	`margenProyectadoSegunCapacity` decimal(14,10),
	`notas` text,
	`otrosCostosUF` decimal(14,4),
	`lineaNegocio` varchar(100),
	`syncedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_data_id` PRIMARY KEY(`id`),
	CONSTRAINT `financial_data_dealId_unique` UNIQUE(`dealId`)
);
