CREATE TABLE `jira_entity_mapping` (
	`id` int AUTO_INCREMENT NOT NULL,
	`onboardingId` int NOT NULL,
	`projectId` int,
	`mappingKey` varchar(255) NOT NULL,
	`mappingVersion` int NOT NULL DEFAULT 1,
	`sourceKey` varchar(100) NOT NULL,
	`jiraIssueType` varchar(100),
	`targetEntityType` enum('milestone','risk','epic','task','user','document','stage_evidence','ignored') NOT NULL,
	`targetEntityId` varchar(100),
	`syncDirection` enum('jira_to_pmo','pmo_to_jira_explicit','none') NOT NULL DEFAULT 'jira_to_pmo',
	`status` enum('proposed','approved','excluded','superseded') NOT NULL DEFAULT 'proposed',
	`metadata` json,
	`approvedBy` int,
	`approvedByName` varchar(200),
	`approvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jira_entity_mapping_id` PRIMARY KEY(`id`),
	CONSTRAINT `jira_entity_mapping_mappingKey_unique` UNIQUE(`mappingKey`)
);
--> statement-breakpoint
CREATE TABLE `jira_import_exception` (
	`id` int AUTO_INCREMENT NOT NULL,
	`onboardingId` int NOT NULL,
	`projectId` int,
	`domain` enum('identity','sow','jira','risks','planning','baseline','milestones','documents','finance','users','other') NOT NULL,
	`sourceKey` varchar(100),
	`reason` text NOT NULL,
	`resolution` text,
	`severity` enum('info','warning','blocking') NOT NULL DEFAULT 'warning',
	`status` enum('open','accepted','resolved','ignored') NOT NULL DEFAULT 'open',
	`resolvedBy` int,
	`resolvedByName` varchar(200),
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jira_import_exception_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jira_project_onboarding` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int,
	`jiraSpaceId` int,
	`jiraProjectKey` varchar(50) NOT NULL,
	`jiraProjectId` varchar(50),
	`jiraProjectName` varchar(255) NOT NULL,
	`status` enum('draft','preflight','mapping','reconciliation','ready','failed') NOT NULL DEFAULT 'draft',
	`currentStep` int NOT NULL DEFAULT 1,
	`sourceSnapshot` json,
	`sourceFingerprint` varchar(64),
	`identitySnapshot` json,
	`mappingVersion` int NOT NULL DEFAULT 1,
	`lastError` text,
	`initiatedBy` int NOT NULL,
	`initiatedByName` varchar(200),
	`activatedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jira_project_onboarding_id` PRIMARY KEY(`id`),
	CONSTRAINT `jira_project_onboarding_jiraProjectKey_unique` UNIQUE(`jiraProjectKey`)
);
--> statement-breakpoint
CREATE TABLE `jira_sync_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` varchar(64) NOT NULL,
	`onboardingId` int,
	`projectId` int,
	`jiraProjectKey` varchar(50) NOT NULL,
	`source` enum('preflight','initial_import','manual','scheduled','retry') NOT NULL,
	`status` enum('running','dry_run','applied','partial','error') NOT NULL,
	`inputCount` int NOT NULL DEFAULT 0,
	`createdCount` int NOT NULL DEFAULT 0,
	`updatedCount` int NOT NULL DEFAULT 0,
	`skippedCount` int NOT NULL DEFAULT 0,
	`errorCount` int NOT NULL DEFAULT 0,
	`details` json,
	`errorMessage` text,
	`triggeredBy` int,
	`triggeredByName` varchar(200),
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`finishedAt` timestamp,
	`durationMs` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `jira_sync_log_id` PRIMARY KEY(`id`),
	CONSTRAINT `jira_sync_log_runId_unique` UNIQUE(`runId`)
);
